# Generated by Django 5.0.6 on 2025-01-11 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_safetynotificationreport_schedule_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='suspicious_images/')),
                ('timestamp', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='is_police',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('customers', 'Customers'), ('moderator', 'Moderator'), ('agent', 'Agent'), ('admin', 'Admin'), ('police', 'Police')], max_length=10),
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policestation', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phnnum', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('image', models.ImageField(upload_to='missing_persons/')),
                ('missing_from', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('is_finished', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('investigating_police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigating_cases', to='home.police')),
            ],
        ),
    ]
