# Generated by Django 5.0.6 on 2025-01-11 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_detected_users_is_police_alter_users_user_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detected',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='detected',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='location',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='missing_from',
        ),
        migrations.AddField(
            model_name='detected',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='home.missingperson'),
        ),
        migrations.AddField(
            model_name='detected',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detected',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_persons/'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('investigating', 'Investigating')], default='open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='police',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detected',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/'),
        ),
        migrations.AlterField(
            model_name='detected',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='investigating_police',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigating_cases', to='home.police'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='phnnum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='policestation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
