# Generated by Django 5.0.6 on 2025-01-11 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_detected_options_remove_detected_case_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='missing_from',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
