# Generated by Django 4.2.17 on 2025-01-14 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_missingperson_photo_missingperson_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('solo', 'Solo'), ('group', 'Group'), ('family', 'Family')], max_length=20, null=True)),
                ('has_bus', models.BooleanField(blank=True, default=False, null=True)),
                ('has_hotel', models.BooleanField(blank=True, default=False, null=True)),
                ('has_meals', models.BooleanField(blank=True, default=False, null=True)),
                ('hotel_category', models.CharField(blank=True, choices=[('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], max_length=1, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('package', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='home.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('meals', models.CharField(blank=True, choices=[('', 'No Meals'), ('breakfast', 'Breakfast'), ('breakfast_lunch', 'Breakfast & Lunch'), ('all_meals', 'All Meals')], max_length=20, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='home.tourpackage')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='DayActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='home.packageday')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('day', 'order')},
            },
        ),
    ]
