# Generated by Django 5.0.6 on 2025-01-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_packageactivity_delete_dayactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='home.bus'),
        ),
    ]
