# Generated by Django 5.0.6 on 2025-01-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_tourpackage_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('package_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_travelers', models.IntegerField(blank=True, null=True)),
                ('seat_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=10, null=True)),
                ('is_cancelled', models.BooleanField(blank=True, default=False, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('passenger_details', models.JSONField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('schedule_version', models.IntegerField(blank=True, default=1, null=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bus')),
                ('bus_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.busbooking')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customers')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tourpackage')),
            ],
            options={
                'db_table': 'package_booking',
                'ordering': ['-booking_date'],
            },
        ),
    ]
